name: Javadoc
on:
  push:
    branches:
      - master

jobs:
  javadoc:
    runs-on: ubuntu-latest
    if: github.repository == 'spotbugs/spotbugs-gradle-plugin'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
<<<<<<< HEAD:.github/workflows/dokka.yml
          java-version-file: .java-version
=======
          java-version: 11
>>>>>>> origin/master:.github/workflows/javadoc.yml
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Generate Groovydoc
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml
      - name: Prepare to Deploy
        run: |
          npm ci
          rm -f .git/hooks/commit-msg
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dokka/html/
